## Analyzing this dataset I can say that this could be a possibility

In [1]:
import pandas as pd

# Load the Welch et al. dataset from a .txt file
df = pd.read_csv('/Users/rodrigo/Desktop/BrainStation/Capstone/DATASETSDIF/HotspotUnseen/hotspot.txt', delimiter=',')

In [3]:
df.head()

,gap_id,mmsi,vessel_class,flag,vessel_length_m,vessel_tonnage_gt,gap_start_timestamp,gap_start_lat,gap_start_lon,gap_start_distance_from_shore_m,gap_end_timestamp,gap_end_lat,gap_end_lon,gap_end_distance_from_shore_m,gap_hours
0,40072d9edfca0cfd28872cbf9e382e0c,111112726,other,NaN,32.064056,139.583282,2018-03-22 08:59:22+00:00,11.847433,-21.832185,384000.0,2018-03-22 22:00:56+00:00,11.412485,-23.689107,384000.0,13.016667
1,52dcbd77bbdad9ee2642f574acf45190,150402949,other,CHN,54.994278,904.204044,2019-01-31 04:09:19+00:00,-45.895618,-60.642950,396000.0,2019-01-31 18:00:44+00:00,-45.808745,-60.654917,392000.0,13.850000
2,22b6d49ed4bb4d017884b6299ed185f4,204201370,other,PRT,15.350000,40.940000,2018-05-27 04:47:20+00:00,37.836315,-29.405573,95000.0,2018-05-28 14:32:01+00:00,37.860093,-29.286443,87000.0,33.733333
3,1abe463d7f61b110c44f1d1b4654a213,204206740,other,PRT,20.000000,77.263333,2019-06-21 12:17:01+00:00,32.190453,-18.031552,98000.0,2019-06-22 18:56:01+00:00,32.119552,-18.123323,109000.0,30.650000
4,72d047a15e33f67c3c5b91c78ff612be,204209840,other,PRT,20.000000,87.435000,2017-07-02 13:13:08+00:00,39.388467,-29.215400,93000.0,2017-07-04 15:30:29+00:00,38.909333,-28.329817,17000.0,50.283333

In [2]:
# Inspect the first few rows of the dataframe
print("AIS Disabling Events Dataset:")
print(df.head())

# Check for missing values in the dataframe
print("\nMissing values in AIS Disabling Events Dataset:")
print(df.isnull().sum())

# Check the data types in the dataframe
print("\nData types in AIS Disabling Events Dataset:")
print(df.dtypes)

AIS Disabling Events Dataset:
                             gap_id       mmsi vessel_class flag  \
0  40072d9edfca0cfd28872cbf9e382e0c  111112726        other  NaN
1  52dcbd77bbdad9ee2642f574acf45190  150402949        other  CHN
2  22b6d49ed4bb4d017884b6299ed185f4  204201370        other  PRT
3  1abe463d7f61b110c44f1d1b4654a213  204206740        other  PRT
4  72d047a15e33f67c3c5b91c78ff612be  204209840        other  PRT

   vessel_length_m  vessel_tonnage_gt        gap_start_timestamp  \
0        32.064056         139.583282  2018-03-22 08:59:22+00:00
1        54.994278         904.204044  2019-01-31 04:09:19+00:00
2        15.350000          40.940000  2018-05-27 04:47:20+00:00
3        20.000000          77.263333  2019-06-21 12:17:01+00:00
4        20.000000          87.435000  2017-07-02 13:13:08+00:00

   gap_start_lat  gap_start_lon  gap_start_distance_from_shore_m  \
0      11.847433     -21.832185                         384000.0
1     -45.895618     -60.642950                         396000.0
2      37.836315     -29.405573                          95000.0
3      32.190453     -18.031552                          98000.0
4      39.388467     -29.215400                          93000.0

           gap_end_timestamp  gap_end_lat  gap_end_lon  \
0  2018-03-22 22:00:56+00:00    11.412485   -23.689107
1  2019-01-31 18:00:44+00:00   -45.808745   -60.654917
2  2018-05-28 14:32:01+00:00    37.860093   -29.286443
3  2019-06-22 18:56:01+00:00    32.119552   -18.123323
4  2017-07-04 15:30:29+00:00    38.909333   -28.329817

   gap_end_distance_from_shore_m  gap_hours
0                       384000.0  13.016667
1                       392000.0  13.850000
2                        87000.0  33.733333
3                       109000.0  30.650000
4                        17000.0  50.283333

Missing values in AIS Disabling Events Dataset:
gap_id                               0
mmsi                                 0
vessel_class                         0
flag                               702
vessel_length_m                      3
vessel_tonnage_gt                    0
gap_start_timestamp                  0
gap_start_lat                        0
gap_start_lon                        0
gap_start_distance_from_shore_m      0
gap_end_timestamp                    0
gap_end_lat                          0
gap_end_lon                          0
gap_end_distance_from_shore_m        0
gap_hours                            0
dtype: int64

Data types in AIS Disabling Events Dataset:
gap_id                              object
mmsi                                 int64
vessel_class                        object
flag                                object
vessel_length_m                    float64
vessel_tonnage_gt                  float64
gap_start_timestamp                 object
gap_start_lat                      float64
gap_start_lon                      float64
gap_start_distance_from_shore_m    float64
gap_end_timestamp                   object
gap_end_lat                        float64
gap_end_lon                        float64
gap_end_distance_from_shore_m      float64
gap_hours                          float64
dtype: object

In [3]:
# Handle missing values
df['flag'].fillna('Unknown', inplace=True)
df['vessel_length_m'].fillna(df['vessel_length_m'].median(), inplace=True)

# Convert timestamps to datetime
df['gap_start_timestamp'] = pd.to_datetime(df['gap_start_timestamp'])
df['gap_end_timestamp'] = pd.to_datetime(df['gap_end_timestamp'])

# Check the dataframe after processing
print("\nProcessed AIS Disabling Events Dataset:")
print(df.info())
print(df.head())

# Save the cleaned and processed dataset
df.to_csv('/Users/rodrigo/Desktop/BrainStation/Capstone/DATASETSDIF/processed_ais_disabling_events.csv', index=False)
print("\nData saved to 'processed_ais_disabling_events.csv'")

Processed AIS Disabling Events Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55368 entries, 0 to 55367
Data columns (total 15 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   gap_id                           55368 non-null  object
 1   mmsi                             55368 non-null  int64
 2   vessel_class                     55368 non-null  object
 3   flag                             55368 non-null  object
 4   vessel_length_m                  55368 non-null  float64
 5   vessel_tonnage_gt                55368 non-null  float64
 6   gap_start_timestamp              55368 non-null  datetime64[ns, UTC]
 7   gap_start_lat                    55368 non-null  float64
 8   gap_start_lon                    55368 non-null  float64
 9   gap_start_distance_from_shore_m  55368 non-null  float64
 10  gap_end_timestamp                55368 non-null  datetime64[ns, UTC]
 11  gap_end_lat                      55368 non-null  float64
 12  gap_end_lon                      55368 non-null  float64
 13  gap_end_distance_from_shore_m    55368 non-null  float64
 14  gap_hours                        55368 non-null  float64
dtypes: datetime64[ns, UTC](2), float64(9), int64(1), object(3)
memory usage: 6.3+ MB
None
                             gap_id       mmsi vessel_class     flag  \
0  40072d9edfca0cfd28872cbf9e382e0c  111112726        other  Unknown
1  52dcbd77bbdad9ee2642f574acf45190  150402949        other      CHN
2  22b6d49ed4bb4d017884b6299ed185f4  204201370        other      PRT
3  1abe463d7f61b110c44f1d1b4654a213  204206740        other      PRT
4  72d047a15e33f67c3c5b91c78ff612be  204209840        other      PRT

   vessel_length_m  vessel_tonnage_gt       gap_start_timestamp  \
0        32.064056         139.583282 2018-03-22 08:59:22+00:00
1        54.994278         904.204044 2019-01-31 04:09:19+00:00
2        15.350000          40.940000 2018-05-27 04:47:20+00:00
3        20.000000          77.263333 2019-06-21 12:17:01+00:00
4        20.000000          87.435000 2017-07-02 13:13:08+00:00

   gap_start_lat  gap_start_lon  gap_start_distance_from_shore_m  \
0      11.847433     -21.832185                         384000.0
1     -45.895618     -60.642950                         396000.0
2      37.836315     -29.405573                          95000.0
3      32.190453     -18.031552                          98000.0
4      39.388467     -29.215400                          93000.0

          gap_end_timestamp  gap_end_lat  gap_end_lon  \
0 2018-03-22 22:00:56+00:00    11.412485   -23.689107
1 2019-01-31 18:00:44+00:00   -45.808745   -60.654917
2 2018-05-28 14:32:01+00:00    37.860093   -29.286443
3 2019-06-22 18:56:01+00:00    32.119552   -18.123323
4 2017-07-04 15:30:29+00:00    38.909333   -28.329817

   gap_end_distance_from_shore_m  gap_hours
0                       384000.0  13.016667
1                       392000.0  13.850000
2                        87000.0  33.733333
3                       109000.0  30.650000
4                        17000.0  50.283333

Data saved to 'processed_ais_disabling_events.csv'

In [4]:
df.shape

(55368, 15)

In [5]:
# Optionally, drop rows with missing critical values or fill them with appropriate values
df.dropna(inplace=True)

In [6]:
# Standardize column names
df.rename(columns={
    'gap_id': 'event_id',
    'mmsi': 'vessel_id',
    'vessel_class': 'vessel_class',
    'flag': 'flag_state',
    'vessel_length_m': 'vessel_length_m',
    'vessel_tonnage_gt': 'vessel_tonnage_gt',
    'gap_start_timestamp': 'start_timestamp',
    'gap_start_lat': 'start_latitude',
    'gap_start_lon': 'start_longitude',
    'gap_start_distance_from_shore_m': 'start_distance_from_shore_m',
    'gap_end_timestamp': 'end_timestamp',
    'gap_end_lat': 'end_latitude',
    'gap_end_lon': 'end_longitude',
    'gap_end_distance_from_shore_m': 'end_distance_from_shore_m',
    'gap_hours': 'gap_hours'
}, inplace=True)

# Confirm changes
print(df.head())

                           event_id  vessel_id vessel_class flag_state  \
1  52dcbd77bbdad9ee2642f574acf45190  150402949        other        CHN
2  22b6d49ed4bb4d017884b6299ed185f4  204201370        other        PRT
3  1abe463d7f61b110c44f1d1b4654a213  204206740        other        PRT
4  72d047a15e33f67c3c5b91c78ff612be  204209840        other        PRT
5  87d87366d2def578701b373d1240a958  204225000        other        PRT

   vessel_length_m  vessel_tonnage_gt            start_timestamp  \
1        54.994278         904.204044  2019-01-31 04:09:19+00:00
2        15.350000          40.940000  2018-05-27 04:47:20+00:00
3        20.000000          77.263333  2019-06-21 12:17:01+00:00
4        20.000000          87.435000  2017-07-02 13:13:08+00:00
5        25.380000         154.000000  2017-12-10 20:05:37+00:00

   start_latitude  start_longitude  start_distance_from_shore_m  \
1      -45.895618       -60.642950                     396000.0
2       37.836315       -29.405573                      95000.0
3       32.190453       -18.031552                      98000.0
4       39.388467       -29.215400                      93000.0
5       38.722653       -30.001233                     102000.0

               end_timestamp  end_latitude  end_longitude  \
1  2019-01-31 18:00:44+00:00    -45.808745     -60.654917
2  2018-05-28 14:32:01+00:00     37.860093     -29.286443
3  2019-06-22 18:56:01+00:00     32.119552     -18.123323
4  2017-07-04 15:30:29+00:00     38.909333     -28.329817
5  2017-12-11 10:03:05+00:00     38.235638     -29.421588

   end_distance_from_shore_m  gap_hours
1                   392000.0  13.850000
2                    87000.0  33.733333
3                   109000.0  30.650000
4                    17000.0  50.283333
5                    65000.0  13.950000

In [7]:
# Convert 'start_timestamp' and 'end_timestamp' to datetime format
df['start_timestamp'] = pd.to_datetime(df['start_timestamp'])
df['end_timestamp'] = pd.to_datetime(df['end_timestamp'])

# Optionally, extract additional time-based features
df['start_year'] = df['start_timestamp'].dt.year
df['start_month'] = df['start_timestamp'].dt.month
df['start_day'] = df['start_timestamp'].dt.day

df['end_year'] = df['end_timestamp'].dt.year
df['end_month'] = df['end_timestamp'].dt.month
df['end_day'] = df['end_timestamp'].dt.day

In [8]:
# Save the cleaned data to a CSV file
df.to_csv('/Users/rodrigo/Desktop/BrainStation/Capstone/DATASETSDIF/HotspotUnseen/cleaned_hotspot.csv', index=False)